http:
  routers:
    api:
      rule: Host(`api.localhost`)
      entryPoints:
        - web
      service: api

  services:
    api:
      loadBalancer:
        servers:
          - url: http://api:8000
